#the file is set to delete all the trival files generated by vs, all needed is the cpp files,

del /S *.exe *.o *.sln *.idb *.pdb *.log *.tlog *.lastbuildstate *.obj *.vcxproj *.filters *.db *.ipch *.suo *.ilk *.sdf